// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/product.proto

package product

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v3/api"
	client "github.com/micro/go-micro/v3/client"
	server "github.com/micro/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Product service

func NewProductEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Product service

type ProductService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Product_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Product_PingPongService, error)
}

type productService struct {
	c    client.Client
	name string
}

func NewProductService(name string, c client.Client) ProductService {
	return &productService{
		c:    c,
		name: name,
	}
}

func (c *productService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Product.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Product_StreamService, error) {
	req := c.c.NewRequest(c.name, "Product.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &productServiceStream{stream}, nil
}

type Product_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type productServiceStream struct {
	stream client.Stream
}

func (x *productServiceStream) Close() error {
	return x.stream.Close()
}

func (x *productServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *productServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *productServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *productServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *productService) PingPong(ctx context.Context, opts ...client.CallOption) (Product_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Product.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &productServicePingPong{stream}, nil
}

type Product_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type productServicePingPong struct {
	stream client.Stream
}

func (x *productServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *productServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *productServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *productServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *productServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *productServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Product service

type ProductHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Product_StreamStream) error
	PingPong(context.Context, Product_PingPongStream) error
}

func RegisterProductHandler(s server.Server, hdlr ProductHandler, opts ...server.HandlerOption) error {
	type product interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Product struct {
		product
	}
	h := &productHandler{hdlr}
	return s.Handle(s.NewHandler(&Product{h}, opts...))
}

type productHandler struct {
	ProductHandler
}

func (h *productHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.ProductHandler.Call(ctx, in, out)
}

func (h *productHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ProductHandler.Stream(ctx, m, &productStreamStream{stream})
}

type Product_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type productStreamStream struct {
	stream server.Stream
}

func (x *productStreamStream) Close() error {
	return x.stream.Close()
}

func (x *productStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *productStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *productStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *productStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *productHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.ProductHandler.PingPong(ctx, &productPingPongStream{stream})
}

type Product_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type productPingPongStream struct {
	stream server.Stream
}

func (x *productPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *productPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *productPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *productPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *productPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *productPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
