// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/category.proto

package category

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v3/api"
	client "github.com/micro/go-micro/v3/client"
	server "github.com/micro/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Category service

func NewCategoryEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Category service

type CategoryService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Category_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Category_PingPongService, error)
}

type categoryService struct {
	c    client.Client
	name string
}

func NewCategoryService(name string, c client.Client) CategoryService {
	return &categoryService{
		c:    c,
		name: name,
	}
}

func (c *categoryService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Category.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Category_StreamService, error) {
	req := c.c.NewRequest(c.name, "Category.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &categoryServiceStream{stream}, nil
}

type Category_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type categoryServiceStream struct {
	stream client.Stream
}

func (x *categoryServiceStream) Close() error {
	return x.stream.Close()
}

func (x *categoryServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *categoryServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *categoryServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *categoryServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *categoryService) PingPong(ctx context.Context, opts ...client.CallOption) (Category_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Category.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &categoryServicePingPong{stream}, nil
}

type Category_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type categoryServicePingPong struct {
	stream client.Stream
}

func (x *categoryServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *categoryServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *categoryServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *categoryServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *categoryServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *categoryServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Category service

type CategoryHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Category_StreamStream) error
	PingPong(context.Context, Category_PingPongStream) error
}

func RegisterCategoryHandler(s server.Server, hdlr CategoryHandler, opts ...server.HandlerOption) error {
	type category interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Category struct {
		category
	}
	h := &categoryHandler{hdlr}
	return s.Handle(s.NewHandler(&Category{h}, opts...))
}

type categoryHandler struct {
	CategoryHandler
}

func (h *categoryHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.CategoryHandler.Call(ctx, in, out)
}

func (h *categoryHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.CategoryHandler.Stream(ctx, m, &categoryStreamStream{stream})
}

type Category_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type categoryStreamStream struct {
	stream server.Stream
}

func (x *categoryStreamStream) Close() error {
	return x.stream.Close()
}

func (x *categoryStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *categoryStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *categoryStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *categoryStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *categoryHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.CategoryHandler.PingPong(ctx, &categoryPingPongStream{stream})
}

type Category_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type categoryPingPongStream struct {
	stream server.Stream
}

func (x *categoryPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *categoryPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *categoryPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *categoryPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *categoryPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *categoryPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
