// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/sync.proto

package sync

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v3/api"
	client "github.com/micro/go-micro/v3/client"
	server "github.com/micro/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Sync service

func NewSyncEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Sync service

type SyncService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Sync_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Sync_PingPongService, error)
}

type syncService struct {
	c    client.Client
	name string
}

func NewSyncService(name string, c client.Client) SyncService {
	return &syncService{
		c:    c,
		name: name,
	}
}

func (c *syncService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Sync.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Sync_StreamService, error) {
	req := c.c.NewRequest(c.name, "Sync.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &syncServiceStream{stream}, nil
}

type Sync_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type syncServiceStream struct {
	stream client.Stream
}

func (x *syncServiceStream) Close() error {
	return x.stream.Close()
}

func (x *syncServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *syncServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *syncServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *syncServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *syncService) PingPong(ctx context.Context, opts ...client.CallOption) (Sync_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Sync.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &syncServicePingPong{stream}, nil
}

type Sync_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type syncServicePingPong struct {
	stream client.Stream
}

func (x *syncServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *syncServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *syncServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *syncServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *syncServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *syncServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Sync service

type SyncHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Sync_StreamStream) error
	PingPong(context.Context, Sync_PingPongStream) error
}

func RegisterSyncHandler(s server.Server, hdlr SyncHandler, opts ...server.HandlerOption) error {
	type sync interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Sync struct {
		sync
	}
	h := &syncHandler{hdlr}
	return s.Handle(s.NewHandler(&Sync{h}, opts...))
}

type syncHandler struct {
	SyncHandler
}

func (h *syncHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.SyncHandler.Call(ctx, in, out)
}

func (h *syncHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.SyncHandler.Stream(ctx, m, &syncStreamStream{stream})
}

type Sync_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type syncStreamStream struct {
	stream server.Stream
}

func (x *syncStreamStream) Close() error {
	return x.stream.Close()
}

func (x *syncStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *syncStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *syncStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *syncStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *syncHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.SyncHandler.PingPong(ctx, &syncPingPongStream{stream})
}

type Sync_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type syncPingPongStream struct {
	stream server.Stream
}

func (x *syncPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *syncPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *syncPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *syncPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *syncPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *syncPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
