// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/shop.proto

package shop

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v3/api"
	client "github.com/micro/go-micro/v3/client"
	server "github.com/micro/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Shop service

func NewShopEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Shop service

type ShopService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Shop_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Shop_PingPongService, error)
}

type shopService struct {
	c    client.Client
	name string
}

func NewShopService(name string, c client.Client) ShopService {
	return &shopService{
		c:    c,
		name: name,
	}
}

func (c *shopService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Shop.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Shop_StreamService, error) {
	req := c.c.NewRequest(c.name, "Shop.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &shopServiceStream{stream}, nil
}

type Shop_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type shopServiceStream struct {
	stream client.Stream
}

func (x *shopServiceStream) Close() error {
	return x.stream.Close()
}

func (x *shopServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *shopServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *shopServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *shopServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *shopService) PingPong(ctx context.Context, opts ...client.CallOption) (Shop_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Shop.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &shopServicePingPong{stream}, nil
}

type Shop_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type shopServicePingPong struct {
	stream client.Stream
}

func (x *shopServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *shopServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *shopServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *shopServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *shopServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *shopServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Shop service

type ShopHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Shop_StreamStream) error
	PingPong(context.Context, Shop_PingPongStream) error
}

func RegisterShopHandler(s server.Server, hdlr ShopHandler, opts ...server.HandlerOption) error {
	type shop interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Shop struct {
		shop
	}
	h := &shopHandler{hdlr}
	return s.Handle(s.NewHandler(&Shop{h}, opts...))
}

type shopHandler struct {
	ShopHandler
}

func (h *shopHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.ShopHandler.Call(ctx, in, out)
}

func (h *shopHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ShopHandler.Stream(ctx, m, &shopStreamStream{stream})
}

type Shop_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type shopStreamStream struct {
	stream server.Stream
}

func (x *shopStreamStream) Close() error {
	return x.stream.Close()
}

func (x *shopStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *shopStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *shopStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *shopStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *shopHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.ShopHandler.PingPong(ctx, &shopPingPongStream{stream})
}

type Shop_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type shopPingPongStream struct {
	stream server.Stream
}

func (x *shopPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *shopPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *shopPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *shopPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *shopPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *shopPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
